-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Aug 04, 2023 at 10:31 PM
-- Server version: 10.4.28-MariaDB
-- PHP Version: 8.0.28

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `recipes`
--

-- --------------------------------------------------------

--
-- Table structure for table `recipes`
--

CREATE TABLE `recipes` (
  `id` int(11) NOT NULL,
  `prepTime` varchar(50) NOT NULL,
  `cookTime` varchar(50) NOT NULL,
  `totalTime` varchar(50) NOT NULL,
  `servings` varchar(50) NOT NULL,
  `image` varchar(100) NOT NULL,
  `ingredients` longtext NOT NULL,
  `directions` longtext NOT NULL,
  `category` varchar(50) NOT NULL,
  `subCategory` varchar(50) NOT NULL,
  `title` varchar(250) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `recipes`
--

INSERT INTO `recipes` (`id`, `prepTime`, `cookTime`, `totalTime`, `servings`, `image`, `ingredients`, `directions`, `category`, `subCategory`, `title`) VALUES
(1, '17 minutes', '17 minutes', '35 minutes', '2-4 servings', 'chinesefrieddough.jpg', '2 cups all-purpose flour, 1/2 teaspoon salt, 1/2 teaspoon baking powder, 3/4 cup water, vegetable oil for frying', '1. In a bowl, mix flour, salt, and baking powder. Gradually add water to form a smooth dough.\n2. Cover and let the dough rest for 30 minutes.\n3. Roll out the dough into a rectangle and cut into strips.\n4. Heat oil in a pan and fry the strips until golden brown.\n5. Serve as a side dish with rice porridge or soy milk soup.', 'Chinese', 'Breakfast', 'Chinese Fried Dough (Youtiao)'),
(2, '7 minutes', '7 minutes', '15 minutes', '2 servings', 'soymilksoup.jpg', 'Fresh soybeans, water, vinegar, sugar', '1. Blend fresh soybeans with water.\n2. Strain the mixture to extract the soy milk.\n3. Heat the soy milk with vinegar and sugar, stirring until it thickens slightly.\n4. Serve with Youtiao or other breakfast items.', 'Chinese', 'Breakfast', 'Chinese Soy Milk Soup(Dou Jiang)'),
(3, '45 minutes', '45 minutes', '1 hour 30 minutes', '4-6 servings', 'congee.jpg', '1 cup long-grain rice, 8 cups chicken or vegetable broth, 2 large eggs, peanuts, green onions, soy sauce', '1. Rinse the rice and combine it with the broth in a pot.\n2. Bring to a boil, then reduce heat and simmer until the rice is fully cooked and the congee thickens.\n3. Beat the eggs and slowly drizzle them into the congee while stirring.\n4. Serve hot with peanuts, green onions, and a dash of soy sauce.', 'Chinese', 'Breakfast', 'Chinese Rice Porridge (Congee)'),
(4, '35 minutes', '35 minutes', '1 hour 10 minutes', '4-6 servings', 'steamedmeatbuns.jpg', '2 cups all-purpose flour, 1/2 teaspoon baking powder, 3/4 cup water, 1 tablespoon vegetable oil, ground meat (pork, chicken, or beef), soy sauce, oyster sauce, sesame oil', '1. Mix flour, baking powder, water, and vegetable oil to form a soft dough.\n2. Let the dough rest for 30 minutes, then roll it out and cut into rounds.\n3. Fill each round with a mixture of ground meat, soy sauce, oyster sauce, and sesame oil.\n4. Steam the buns until cooked through and serve hot.', 'Chinese', 'Breakfast', 'Steamed Meat Buns (Baozi)'),
(5, '15 minutes', '15 minutes', '30 minutes', '2-3 servings', 'steameddumplings.jpg', '1/2 pound ground pork, 1/4 cup chopped shrimp, 2 tablespoons soy sauce, 1 tablespoon oyster sauce, 1 tablespoon sesame oil, wonton wrappers', '1. Mix ground pork, chopped shrimp, soy sauce, oyster sauce, and sesame oil.\n2. Place a spoonful of the filling in the center of each wonton wrapper.\n3. Fold the wrapper over the filling and seal the edges.\n4. Steam the dumplings until cooked and serve with dipping sauce.', 'Chinese', 'Breakfast', 'Chinese Steamed Dumplings (Shumai)'),
(6, '35 minutes', '35 minutes', '1 hour 10 minutes', '4-6 servings', 'frieddumplings.jpg', '1/2 pound ground pork, 1/4 cup chopped cabbage, 2 tablespoons soy sauce, 1 tablespoon sesame oil, round dumpling wrappers', '1. Mix ground pork, chopped cabbage, soy sauce, and sesame oil.\n2. Place a spoonful of the filling in the center of each dumpling wrapper.\n3. Fold the wrapper over the filling and seal the edges.\n4. Heat oil in a pan and fry the dumplings until crispy and golden brown.\n5. Serve with vinegar, soy sauce, and minced garlic for dipping.', 'Chinese', 'Breakfast', 'Chinese Fried Dumplings (Jiaozi)'),
(7, '12.5 minutes', '12.5 minutes', '25 minutes', '2-4 servings', 'wontonsoup.jpg', '1/2 pound ground pork, 1/4 cup chopped shrimp, 2 tablespoons soy sauce, 1 tablespoon sesame oil, wonton wrappers, chicken broth, bok choy, mushrooms, ginger, vinegar', '1. Mix ground pork, chopped shrimp, soy sauce, and sesame oil.\n2. Place a spoonful of the filling in the center of each wonton wrapper.\n3. Fold the wrapper over the filling and seal the edges.\n4. Bring chicken broth to a boil and add sliced ginger, bok choy, and mushrooms.\n5. Add the wontons and cook until they float to the surface.\n6. Serve hot with a drizzle of vinegar.', 'Chinese', 'Breakfast', 'Wonton Soup'),
(8, '15 minutes', '15 minutes', '30 minutes', '2 servings', 'chinesecrepe.jpg', '1 cup all-purpose flour, 1 cup water, 2 large eggs, scallions, vegetable oil, soybean paste, chili garlic paste', '1. Whisk flour and water together to form a smooth batter.\n2. Beat the eggs and add them to the batter.\n3. Heat a non-stick pan with oil and pour in the batter.\n4. Sprinkle chopped scallions on top and cook until the crepe is set.\n5. Spread soybean paste and chili garlic paste on the crepe, then fold it in half and serve.', 'Chinese', 'Breakfast', 'Chinese Crepe(Jian Bing)'),
(9, '45 minutes', '45 minutes', '1 hour 30 minutes', '4-6 servings', 'scallionpancake.jpg', '2 cups all-purpose flour, 3/4 cup hot water, 1/2 cup chopped scallions, salt, vegetable oil, soy sauce', '1. Mix flour and hot water to form a smooth dough.\n2. Let the dough rest for 1 hour, then roll it out into a thin rectangle.\n3. Sprinkle chopped scallions and salt on top of the dough.\n4. Roll up the dough and then roll it out again.\n5. Cook the pancake in a pan with oil until golden brown on both sides.\n6. Serve with soy sauce for dipping.', 'Chinese', 'Breakfast', 'Chinese Scallion Pancake(Cong You Bing)'),
(10, '1 hour 15 minutes', '1 hour 15 minutes', '2 hours 30 minutes', '6-8 servings', 'turnipcake.jpg', '2 cups rice flour, 1 cup grated turnip, dried shrimp, Chinese sausage, mushrooms, soy sauce, chicken broth', '1. Mix rice flour and grated turnip to form a sticky batter.\n2. Add dried shrimp, Chinese sausage, mushrooms, and soy sauce to the batter.\n3. Steam the mixture in a pan until it solidifies into a cake.\n4. Cool and slice the cake into pieces.\n5. Pan-fry the pieces until crispy and serve.', 'Chinese', 'Breakfast', 'Chinese Turnip Cake(Lou Pak Gou)'),
(11, '12.5 minutes', '12.5 minutes', '25 minutes', '2 servings', 'scallionoilnoodles.jpg', '8 oz wheat noodles, scallions, vegetable oil, sugar, soy sauce', '1. Cook wheat noodles according to package instructions.\n2. Chop scallions and sauté them in hot oil.\n3. Mix the scallion oil with cooked noodles.\n4. Sprinkle sugar and soy sauce on top for seasoning.\n5. Toss everything together and serve hot.', 'Chinese', 'Breakfast', 'Chinese Scallion Oil Noodles(Cong You Ban Mian)'),
(12, '20 min', '10 min', '30 min', '4 servings', 'CashewChicken.jpg', '1 lb boneless, skinless chicken thighs or breasts, cut into bite-sized pieces\n¼ cup soy sauce\n2 Tbsp oyster sauce\n2 Tbsp Shaoxing wine\n1 Tbsp cornstarch\n1 Tbsp vegetable oil\n1 cup unsalted cashews\n1 red bell pepper, cut into bite-sized pieces\n1 green bell pepper, cut into bite-sized pieces\n1 small onion, cut into bite-sized pieces\n3 cloves garlic, minced\n1-inch piece ginger, minced\n2 green onions, sliced', '1. Mix soy sauce, oyster sauce, Shaoxing wine, and cornstarch to create marinade.\n2. Marinate chicken pieces for 10 minutes.\n3. Stir-fry chicken until cooked. Set aside.\n4. Stir-fry cashews until toasted. Set aside.\n5. Stir-fry bell peppers, onion, garlic, and ginger until softened.\n6. Add chicken, cashews, and green onions. Toss.\n7. Serve Cashew Chicken hot with rice or noodles.', 'Chinese', 'MainDishes', 'Cashew Chicken'),
(13, '20 min', '10 min', '30 min', '4 servings', 'BeefandBroccoliStirFry.jpg', '1 lb flank steak or sirloin, thinly sliced\n¼ cup low-sodium soy sauce\n3 Tbsp oyster sauce\n1 Tbsp cornstarch\n1 Tbsp vegetable oil\n1 lb broccoli florets\n3 cloves garlic, minced\n1-inch piece ginger, minced\n2 green onions, sliced\n1 Tbsp sesame oil\nToasted sesame seeds (optional)', '1. Mix soy sauce, oyster sauce, and cornstarch for marinade.\n2. Marinate beef for 10 minutes.\n3. Stir-fry beef until cooked. Set aside.\n4. Stir-fry broccoli until tender-crisp.\n5. Add garlic and ginger. Stir-fry until fragrant.\n6. Return beef to wok with broccoli, garlic, and ginger. Toss.\n7. Drizzle with sesame oil and garnish with sesame seeds if desired.\n8. Serve Beef and Broccoli Stir-Fry hot with rice or noodles.', 'Chinese', 'MainDishes', 'Beef and Broccoli Stir Fry'),
(14, '15 min', '10 min', '25 min', '4 servings', 'KungPaoTofu.jpg', '1 block (14 oz) firm tofu, cubed\n¼ cup cornstarch\n3 Tbsp vegetable oil, divided\n3 dried red chilies, deseeded\n2 tsp Sichuan peppercorns\n3 cloves garlic, minced\n1-inch piece ginger, minced\n2 green onions, sliced\n½ cup unsalted roasted peanuts\nMarinade: 2 Tbsp soy sauce, 1 Tbsp Shaoxing wine, 1 tsp cornstarch\nSauce: 2 Tbsp soy sauce, 1 Tbsp black vinegar, 1 Tbsp hoisin sauce, 1 tsp sesame oil, 2 tsp sugar, ¼ cup vegetable broth, 1 tsp cornstarch, 1 Tbsp water', '1. Marinate tofu in soy sauce, Shaoxing wine, and cornstarch.\n2. Coat tofu with cornstarch and fry until golden.\n3. Stir-fry dried chilies and Sichuan peppercorns until fragrant.\n4. Add garlic and ginger. Stir-fry until fragrant.\n5. Mix ingredients for sauce.\n6. Add sauce to wok and simmer.\n7. Add tofu, peanuts, and green onions. Toss.\n8. Serve Kung Pao Tofu hot with rice.', 'Chinese', 'MainDishes', 'Kung Pao Tofu'),
(15, '20 min', '10 min', '30 min', '4 servings', 'OrangeChicken.jpg', '1 lb boneless, skinless chicken thighs or breasts, cut into bite-sized pieces\n½ cup cornstarch\n3 large eggs, beaten\n¼ cup vegetable oil, for frying\n1 Tbsp vegetable oil, for stir-frying\n1 cup chicken broth\n½ cup orange juice\n¼ cup granulated sugar\n3 Tbsp soy sauce\n3 Tbsp rice vinegar\n2 cloves garlic, minced\n1-inch piece ginger, minced\nZest of 1 orange\n1 Tbsp cornstarch\n2 Tbsp water\nSesame seeds and sliced green onions (optional)', '1. Coat chicken with cornstarch, then dip in beaten eggs.\n2. Fry chicken until golden and crispy. Set aside.\n3. Stir-fry garlic and ginger until fragrant.\n4. Mix chicken broth, orange juice, sugar, soy sauce, and rice vinegar for the sauce.\n5. Add sauce and orange zest to wok. Simmer.\n6. Mix cornstarch and water for thickening. Add to the sauce.\n7. Add fried chicken to wok. Toss until coated.\n8. Garnish with sesame seeds and green onions if desired.\n9. Serve Orange Chicken hot with rice.', 'Chinese', 'MainDishes', 'Orange Chicken'),
(16, '15 min', '10 min', '25 min', '4 servings', 'HunanBeef.jpg', '1 lb flank steak or sirloin, thinly sliced against the grain\n¼ cup soy sauce\n3 Tbsp hoisin sauce\n1 Tbsp rice vinegar\n1 Tbsp vegetable oil\n1 Tbsp cornstarch\n1 Tbsp brown sugar\n1 tsp sesame oil\n2 tsp vegetable oil, for stir-frying\n4-6 dried red chilies, deseeded and cut into small pieces\n3 cloves garlic, minced\n1-inch piece ginger, minced\n1 red bell pepper, cut into thin strips\n1 green bell pepper, cut into thin strips\n2 green onions, sliced\nToasted sesame seeds (optional)', '1. Mix soy sauce, hoisin sauce, rice vinegar, vegetable oil, cornstarch, brown sugar, and sesame oil for marinade.\n2. Marinate beef for 10 minutes.\n3. Stir-fry beef until cooked. Set aside.\n4. Stir-fry dried red chilies, garlic, and ginger until fragrant.\n5. Add bell peppers. Stir-fry until slightly softened.\n6. Return beef to wok with vegetables. Toss.\n7. Garnish with sesame seeds if desired.\n8. Serve Hunan Beef hot with rice.', 'Chinese', 'MainDishes', 'Hunan Beef'),
(17, '15 min', '10 min', '25 min', '4 servings', 'BroccoliBeef.jpg', '1 lb flank steak or sirloin, thinly sliced against the grain\n¼ cup soy sauce\n3 Tbsp oyster sauce\n1 Tbsp cornstarch\n1 Tbsp vegetable oil\n1 lb broccoli florets\n3 cloves garlic, minced\n1-inch piece ginger, minced\n2 green onions, sliced\nToasted sesame seeds (optional)', '1. Mix soy sauce, oyster sauce, and cornstarch for marinade.\n2. Marinate beef for 10 minutes.\n3. Stir-fry beef until cooked. Set aside.\n4. Stir-fry broccoli until tender-crisp.\n5. Add garlic and ginger. Stir-fry until fragrant.\n6. Return beef to wok with broccoli, garlic, and ginger. Toss.\n7. Garnish with sesame seeds if desired.\n8. Serve Broccoli Beef hot with rice.', 'Chinese', 'MainDishes', 'Broccoli Beef'),
(18, '2h 40 min', '4h', '6h 40 min', '4 - 6 servings', 'slow-cookerchickenwings.jpg', '3 lb(s) chicken wings, split\nKosher salt\n¼ cup honey\n¼ cup hoisin sauce\n3 tbsp low-sodium soy sauce\n2 tbsp oyster sauce\n1 tbsp minced fresh ginger\n¼ tsp Chinese five-spice powder\n2 scallions, thinly sliced on a bias, for serving', '1. Season chicken wings with kosher salt and place them in a slow cooker.\n2. Mix honey, hoisin sauce, soy sauce, oyster sauce, minced ginger, and Chinese five-spice powder in a bowl.\n3. Pour the sauce mixture over the chicken wings, making sure they are well coated.\n4. Cover the slow cooker and cook on low heat for about 4 hours, or until the chicken is tender and fully cooked.\n5. Once cooked, transfer the chicken wings to a serving dish and garnish with sliced scallions.\n6. Serve the slow-cooker chicken wings as a delicious meal or appetizer.', 'Chinese', 'MainDishes', 'Slow-Cooker Chicken Wings'),
(19, '10 minutes', '10 minutes', '20 minutes', '2 servings', 'steamedeggs.jpg', '4 large eggs, chicken stock, soy sauce, sugar, sesame oil', '1. Whisk eggs with chicken stock and strain the mixture.\n2. Steam the egg mixture until it solidifies.\n3. Drizzle soy sauce, sugar, and sesame oil on top.\n4. Serve the smooth and savory steamed eggs.', 'Chinese', 'Breakfast', 'Chinese Steamed Eggs(Zheng Dan)'),
(20, '10 min', '10 min', '20 min', '4 servings', 'CantoneseChowMein.jpg', '1lb chow mein noodles，Neutral high heat oil，1bunch scallions(6-8), cut into 2-inch pieces, white and green parts separated，½white onion, thinly sliced，3½cups mung bean sprouts (optional to pinch off head and tail – I don’t)，2tsp sesame oil', '1. Cook the chow mein noodles according to package instructions. Drain and set aside.\n2. Heat a wok over high heat. Add a few tablespoons of neutral high-heat oil and add the onions and the white parts of the scallions. Stir-fry for 1-2 minutes.\n3. Add the mung bean sprouts (if using) and stir-fry for an additional 1-2 minutes.\n4. Add the cooked chow mein noodles to the wok and stir-fry with the vegetables.\n5. Add the sesame oil and stir-fry for another 1-2 minutes.\n6. Serve the Cantonese Chow Mein hot, garnished with the green parts of the scallions.', 'Chinese', 'MainDishes', 'Cantonese Chow Mein'),
(21, '40 min', '10 min', '50 min', '28-30 dumplings', 'FriedSweetPeanutDumplings.jpg', '½ cup raw unsalted peanuts\n¼ cup caster sugar\n⅓ cup raw sesame seeds\n1 Tbsp unsweetened shredded coconut', '1. In a medium pan over medium heat, add the peanuts and dry-fry them until they are golden brown. Set them aside to cool.\n2. Once the peanuts have cooled, add them to a food processor with the sugar, sesame seeds, and shredded coconut.\n3. Pulse the mixture until it is well combined and resembles a coarse powder.\n4. Wet the edges of each dumpling wrapper with a bit of water to help seal them.\n5. Place a teaspoon of the peanut mixture into the center of each dumpling wrapper.\n6. Fold the dumpling wrapper in half and seal the edges by pressing them together.\n7. In a deep saucepan or pot, heat oil over medium heat until it reaches 350°F (175°C).\n8. Fry the dumplings in batches until they are golden brown and crispy.\n9. Remove the dumplings from the oil and drain on a paper towel.\n10. Serve the Fried Sweet Peanut Dumplings as a delightful dessert or snack.', 'Chinese', 'Snacks', 'Fried Sweet Peanut Dumplings'),
(22, '8 minutes', '9 minutes', '17 minutes', '2 servings', 'oguratoast.jpg', 'Japanese bread (Shokupan), butter, sweet azuki red bean paste, whipped cream', '1. Toast the Japanese bread until golden brown.\n2. Spread butter on one side of the toast.\n3. Spread sweet azuki red bean paste on top of the butter.\n4. Add a dollop of whipped cream on the side.\n5. Enjoy your Ogura Toast!', 'Japanese', 'Breakfast', 'Ogura Toast'),
(23, '5 minutes', '12 minutes', '17 minutes', '1 serving', 'okayu.jpg', 'Japanese rice, water, honey, ginger, toppings of your choice (e.g., pickles, nori, sesame seeds)', '1. Rinse the rice thoroughly.\n2. In a pot, bring water and rice to a boil, then reduce heat and simmer until rice becomes soft and creamy.\n3. Stir in honey and grated ginger.\n4. Serve the okayu hot with your favorite toppings.', 'Japanese', 'Breakfast', 'Okayu'),
(24, '10 minutes', '7 minutes', '17 minutes', '1 serving', 'oyakodon.jpg', 'Eggs, dashi, mirin, soy sauce, boneless chicken breasts, onion, cooked Japanese rice, green onions', '1. In a bowl, whisk together eggs, dashi, mirin, and soy sauce.\n2. In a non-stick pan, cook the chicken and onions until cooked through.\n3. Pour the egg mixture over the chicken and onions.\n4. Cook until the eggs are soft and slightly runny.\n5. Serve the oyakodon over a bowl of hot Japanese rice and garnish with green onions.', 'Japanese', 'Breakfast', 'Oyakodon'),
(25, '8 minutes', '10 minutes', '18 minutes', '1 serving', 'skilletokonomiyaki.jpg', 'Eggs, flour, dashi, cabbage, onion, rice, squid, mushrooms, sausage, maize (optional)', '1. In a bowl, whisk together eggs, flour, dashi, and a pinch of salt.\n2. Stir in chopped cabbage, onions, rice, squid, mushrooms, sausage, and maize (if using).\n3. In a non-stick pan, pour the mixture and cook until golden brown on both sides.\n4. Serve the skillet okonomiyaki hot with your favorite toppings.', 'Japanese', 'Breakfast', 'Skillet Okonomiyaki'),
(26, '10 minutes', '10 minutes', '20 minutes', '2 servings', 'japanesepancakes.jpg', 'Eggs, milk, sugar, flour, baking powder, vanilla extract, butter, whipped cream, strawberries', '1. In a bowl, whisk together eggs, milk, sugar, flour, baking powder, and vanilla extract.\n2. In a non-stick pan, pour the pancake batter and cook until bubbles form on the surface.\n3. Flip and cook until golden brown.\n4. Serve the Japanese pancakes with a dollop of butter, whipped cream, and fresh strawberries on top.', 'Japanese', 'Breakfast', 'Japanese Pancakes'),
(27, '10 minutes', '5 minutes', '15 minutes', '1 serving', 'onigiri.jpg', 'Japanese rice, fillings of your choice (e.g., salmon and avocado, tuna mayonnaise), dried seaweed', '1. Wet your hands with water.\n2. Take a handful of rice and flatten it in your hand.\n3. Place your choice of filling in the center and wrap the rice around it.\n4. Shape the rice into a triangle or ball.\n5. Wrap the onigiri with dried seaweed.\n6. Repeat for the remaining rice and filling.\n7. Serve the onigiri as a delicious and portable breakfast snack.', 'Japanese', 'Breakfast', 'Onigiri'),
(28, '5 minutes', '5 minutes', '10 minutes', '1 serving', 'tamagoyaki.jpg', 'Eggs, salt, soy sauce, sugar, mirin, vegetables or cheese (optional)', '1. In a bowl, whisk together eggs, salt, soy sauce, sugar, and mirin.\n2. In a rectangular frying pan, heat some oil and pour a thin layer of egg mixture.\n3. Once the bottom is set, roll up the egg from one end to the other.\n4. Push the rolled egg to one end of the pan and add more egg mixture to fill the space.\n5. Repeat the rolling process until all the egg mixture is used up.\n6. Serve the tamagoyaki hot and sliced into bite-sized pieces.', 'Japanese', 'Breakfast', 'Tamagoyaki'),
(29, '5 minutes', '5 minutes', '10 minutes', '1 serving', 'misobreakfastoats.jpg', 'Instant oats, miso paste, kale, soy sauce, sesame seeds', '1. In a pot, cook the instant oats according to package instructions.\n2. Stir in miso paste, chopped kale, and a dash of soy sauce.\n3. Cook until the kale is wilted and the oats are creamy.\n4. Sprinkle with sesame seeds.\n5. Serve the miso breakfast oats hot and enjoy the savory flavors.', 'Japanese', 'Breakfast', 'Miso Breakfast Oats'),
(30, '10 minutes', '5 minutes', '15 minutes', '1 serving', 'breakfastbento.jpg', 'Assorted cheeses, deli meats, fruits, vegetables, rice balls, nori', '1. Prepare a bento box with different compartments.\n2. Fill the compartments with assorted cheeses, deli meats, fruits, and vegetables.\n3. Add rice balls and wrap them with nori.\n4. Close the bento box and enjoy your breakfast on the go!', 'Japanese', 'Breakfast', 'Breakfast Bento Box'),
(31, '2 minutes', '1 minute', '3 minutes', '1 serving', 'tamagokakegohan.jpg', 'Japanese rice, raw egg', '1. Cook the Japanese rice until hot and fluffy.\n2. Crack a raw egg on top of the hot rice.\n3. Stir the egg into the rice until the rice becomes creamy.\n4. Serve the tamago kake gohan with optional toppings like soy sauce or furikake.', 'Japanese', 'Breakfast', 'Tamago Kake Gohan'),
(32, '5 minutes', '5 minutes', '10 minutes', '1 serving', 'californiarollavocadotoast.jpg', 'Japanese rice, avocado, imitation crab meat, soy sauce', '1. Toast the Japanese rice until crispy.\n2. Mash the avocado and spread it on top of the rice.\n3. Top with imitation crab meat and drizzle with soy sauce.\n4. Enjoy the fusion of California roll and avocado toast!', 'Japanese', 'Breakfast', 'California Roll Avocado Toast'),
(33, '10 minutes', '15 minutes', '25 minutes', '8 servings', 'japaneseredbeanbuns.jpg', 'All-purpose flour, sugar, active dry yeast, milk, unsalted butter, smooth or chunky red bean paste', '1. In a bowl, mix together flour, sugar, and active dry yeast.\n2. Heat milk and melt butter, then add to the dry ingredients.\n3. Knead the dough until smooth and let it rise.\n4. Divide the dough into small balls and flatten.\n5. Fill each dough with red bean paste and seal the edges.\n6. Let the buns rise again and then bake until golden brown.\n7. Serve the Japanese red bean buns warm and enjoy the delightful flavors!', 'Japanese', 'Breakfast', 'Japanese Red Bean Buns'),
(34, '5 minutes', '5 minutes', '10 minutes', '1 serving', 'matchaovernightoats.jpg', 'Rolled oats, almond milk, honey, matcha powder, toppings of your choice (e.g., berries, nuts, coconut flakes)', '1. In a jar, mix rolled oats, almond milk, honey, and matcha powder.\n2. Stir well, cover, and refrigerate overnight.\n3. In the morning, top with your favorite berries, nuts, and coconut flakes.\n4. Enjoy the refreshing and energizing matcha overnight oats!', 'Japanese', 'Breakfast', 'Matcha Overnight Oats'),
(35, '5 minutes', '5 minutes', '10 minutes', '1 serving', 'japanesefruitsandwich.jpg', 'Japanese milk bread, fresh fruits (e.g., strawberries, kiwi, banana), whipped cream', '1. Cut the Japanese milk bread into slices.\n2. Fill the bread with slices of fresh fruits.\n3. Add a dollop of whipped cream on top of the fruits.\n4. Close the sandwich with another slice of bread.\n5. Serve the Japanese fruit sandwich as a delightful and colorful breakfast option.', 'Japanese', 'Breakfast', 'Japanese Fruit Sandwich'),
(36, '15 minutes', '30 minutes', '45 minutes', '1 loaf', 'japanesemilkbread.jpg', 'Bread flour, sugar, salt, milk, unsalted butter, active dry yeast', '1. In a bowl, mix together bread flour, sugar, salt, and active dry yeast.\n2. Heat milk and melt butter, then add to the dry ingredients.\n3. Knead the dough until smooth and let it rise.\n4. Punch down the dough and shape it into a loaf.\n5. Let the dough rise again and then bake until golden brown.\n6. Slice the Japanese milk bread and enjoy its soft and fluffy texture!', 'Japanese', 'Breakfast', 'Japanese Milk Bread'),
(37, '10 minutes', '5 minutes', '15 minutes', '1 serving', 'misoshiru.jpg', 'Instant miso soup, dashi-infused soy paste, vegetables (e.g., tofu, green onions, seaweed)', '1. Prepare instant miso soup according to package instructions.\n2. Add vegetables of your choice, such as tofu, green onions, and seaweed.\n3. Serve the miso shiru hot for a comforting and nourishing breakfast.', 'Japanese', 'Breakfast', 'Miso Shiru'),
(38, '50 minutes', '2 hours 15 minutes', '18 hours 55 minutes', '6-8 servings', 'chashu.jpg', '2 to 2 1/2 pounds pork belly, soy sauce, sake, mirin, brown sugar, garlic, ginger, green onions, vegetable oil', '1. In a pot, combine soy sauce, sake, mirin, brown sugar, garlic, ginger, and green onions.\n2. Add the pork belly and bring to a boil. Reduce heat and simmer until the pork is tender.\n3. Let the pork cool in the liquid, then refrigerate for at least 15 hours.\n4. Slice the pork and serve as a topping for ramen or rice dishes.', 'Japanese', 'MainDishes', 'Chashu(Japanese Braised Pork Belly)'),
(39, '15 minutes', '45 minutes', '60 minutes', '4 servings', 'veganmisoramen.jpg', 'Ramen noodles, vegetable broth, miso paste, coconut milk, soy sauce, sesame oil, garlic, ginger, mushrooms, baby spinach, green onions', '1. Cook ramen noodles according to package instructions.\n2. In a pot, combine vegetable broth, miso paste, coconut milk, soy sauce, sesame oil, garlic, and ginger.\n3. Add mushrooms and baby spinach, and simmer until vegetables are cooked.\n4. Serve the ramen with the creamy vegan miso butter sauce and garnish with green onions.', 'Japanese', 'MainDishes', 'Creamy Vegan Miso Butter Ramen'),
(40, '15 minutes', '12 minutes', '42 minutes', '4 servings', 'chickenkatsu.jpg', 'Chicken breasts, flour, eggs, panko breadcrumbs, salt, black pepper, vegetable oil, shredded cabbage, tonkatsu sauce', '1. Flatten chicken breasts and season with salt and black pepper.\n2. Dredge chicken in flour, dip in beaten eggs, and coat with panko breadcrumbs.\n3. Fry the chicken cutlets in hot oil until golden brown and cooked through.\n4. Serve the chicken katsu with shredded cabbage and drizzle with tonkatsu sauce.', 'Japanese', 'MainDishes', 'Chicken Katsu Recipe'),
(41, '45 minutes', '0 minutes', '45 minutes', '4-6 servings', 'tunasashimi.jpg', 'Fresh tuna, daikon radish, ginger, soy sauce, mirin, green onions, sesame seeds', '1. Slice the fresh tuna into sashimi pieces.\n2. Grate the daikon radish and squeeze out excess water.\n3. Mix soy sauce, mirin, and grated ginger for dipping sauce.\n4. Arrange tuna slices on a plate, garnish with grated daikon and sliced green onions.\n5. Serve the tuna sashimi with daikon and ginger dipping sauce.', 'Japanese', 'MainDishes', 'Tuna Sashimi With Daikon and Ginger'),
(42, '15 minutes', '30 minutes', '45 minutes', '4 servings', 'katsudon.jpg', 'Pork cutlets, onions, eggs, soy sauce, mirin, sugar, dashi broth, cooked Japanese rice, green onions', '1. Slice onions and cook with soy sauce, mirin, sugar, and dashi broth.\n2. Add the pork cutlets to the simmering sauce.\n3. Beat eggs and pour over the pork and onions.\n4. Cover and cook until the eggs are set.\n5. Serve the katsudon over a bowl of hot Japanese rice and garnish with green onions.', 'Japanese', 'MainDishes', 'Katsudon Pork Cutlet Rice Bowl'),
(43, '5 minutes', '15 minutes', '20 minutes', '4 servings', 'gyudon.jpg', 'Sliced beef, onions, soy sauce, mirin, sugar, dashi broth, cooked Japanese rice, green onions', '1. Cook sliced beef and onions with soy sauce, mirin, sugar, and dashi broth.\n2. Simmer until the onions are tender and the beef is cooked.\n3. Serve the gyudon over a bowl of hot Japanese rice and garnish with green onions.', 'Japanese', 'MainDishes', 'Gyudon Recipe'),
(44, '10 minutes', '30 minutes', '40 minutes', '2-3 servings', 'unagieel.jpg', 'Unagi eel, soy sauce, mirin, sugar, sake, Japanese rice', '1. Preheat broiler and grill unagi eel until heated through.\n2. Make a sauce with soy sauce, mirin, sugar, and sake.\n3. Brush the sauce over the grilled eel.\n4. Serve the broiled unagi eel over a bed of hot Japanese rice.', 'Japanese', 'MainDishes', 'Broiled Unagi Eel With Rice'),
(45, '15 minutes', '15 minutes', '30 minutes', '2 servings', 'misoramen.jpg', 'Ramen noodles, miso paste, soy sauce, mirin, vegetable broth, tofu, corn, nori, green onions', '1. Cook ramen noodles according to package instructions.\n2. In a pot, combine miso paste, soy sauce, mirin, and vegetable broth.\n3. Add tofu, corn, and cooked ramen noodles.\n4. Serve the miso ramen hot with nori and green onions as toppings.', 'Japanese', 'MainDishes', 'Miso Ramen Japanese Soup'),
(46, '75 minutes', '35 minutes', '110 minutes', '4-6 servings', 'gingergarlicwings.jpg', 'Chicken wings, soy sauce, mirin, sugar, garlic, ginger, sake', '1. Marinate chicken wings in a mixture of soy sauce, mirin, sugar, garlic, ginger, and sake.\n2. Preheat oven and bake the wings until golden and crispy.\n3. Serve the ginger and garlic chicken wings as a flavorful breakfast option.', 'Japanese', 'MainDishes', 'Ginger and Garlic Chicken Wings'),
(54, '10 min', '30 min', '40 min', '6 servings', 'afang.jpg', '15 cups Sliced fresh waterleaves,\r\n1/2 cup of ground crayfish,\r\n3 cups Ground fresh Ukazi leaves,\r\n3 cubes of knorr (sweetener),\r\n1 stockfish head (medium size),\r\n2 medium-sized dried or roasted fish,\r\n1.5 cups of palm oil,\r\n1 cup of Periwinkles (optional),\r\nSnails (optional),\r\nSalt and Pepper to taste,\r\n6 Red fresh pepper,\r\n2 KG Assorted meat', '1. Grind the ukazi leaves, it acts as the thickener for this soup.\r\n2. Season the meat with a half cup of sliced onions, salt, two seasoning cubes and other spice of choice)\r\n3. Slice the water leaves and set aside in a sieve so excess water will drain away.\r\n4. Wash the stockfish, dried fish and add them to the cooking meat, let them cook till they are soft and the pot is almost dry.\r\n5. Add the palm oil, crayfish and stir all together. Add one seasoning cube, ground pepper, snails and salt to taste, allow cooking for 3-5 minutes.\r\n6. Add the water-leaves; allow to simmer for 6 minutes while you stir continuously.\r\n7. Add the ground ukazi leaves. Stir all together, cover the pot and allow another 5 minutes, stirring every 2 minutes.\r\nand you are done with a delicious afang soup.\r\n8. Serve with eba, fufu or pounded yam', 'African', 'MainDishes', 'Afang soup'),
(55, '10 min', '10 min', '20 min', '6 se', 'efoRiro.jpg', 'Bunches of green vegetables (efo tete) subtitute with fresh or frozen spinach,\r\n\r\nRed bell peppers (tatashe),\r\n\r\nScotch bonnet chillies,\r\n\r\nOnions,\r\n\r\nPalm oil,\r\n\r\nLocust beans (Iru woro),\r\n\r\nDried shawa/palamu (dried smelt fish),\r\n\r\nSmoked mackerel,\r\n\r\nSmoked ponmo, washed and diced,\r\n\r\nGround crayfish,\r\n\r\nSalt,\r\n\r\nSeasoning', '1. Pick the vegetable from the stalk and slice into chunks\r\n2. Rinse vegetable clean, drain and set aside\r\n3. Wash locust beans and set aside\r\n4. Chop 1 onion and set aside\r\n5. Shred the smoked fish into flakes and also set aside\r\n6. Roughly chop the bell pepper (tatashe) and onions, add to a blender and pulse for coarse texture (alternatively, use a food processor for perfect coarse texture)\r\n7. Place a pan on medium heat and add palm oil, heat for about 5 minutes but don’t bleach\r\n8. Followed by iru woro, chopped onions and fry in the oil for about 2 minutes (In this case I used half of the locust beans and saved the rest to be used before I finished cooking the soup). Add blended pepper to the palm oil and stir to combine, after about 3 minutes, add the remaining locust beans. Move on to add the diced ponmo and ground crayfish and cook for another 3-4 minutes on low heat.\r\n9. Add seasoning and pinch of salt. (check for salt at the later stage of the cooking)\r\n10. Whilst you are waiting for the sauce to cook, boil water enough to cover the vegetable. Once the water is boiled, pour over the vegetable and cover with a lid for 5-10 minutes. Strain and squeeze out excess water from the vegetable.\r\n11. Continue to cook the sauce till oil floats on the top, add half of the smoked fish, dried smelt fish and stir to combine. (You can add little water to the sauce if it is too dry but do not overdo it as efo riro is almost water free)\r\n12. Add the vegetable to the sauce and stir till all is well incorporated.\r\n13. Add the remaining smoked mackerel and carefully combine in the vegetable. Check for salt and cook for another 4 minutes. Take it off the heat and set aside. Serve efo riro soup with a swallow of choice or rice and you can even choose to eat it on its own.\r\n\r\n\r\n', 'African', 'MainDishes', 'Efo riro'),
(56, '10', '30', '40', '2', 'akara.jpg', '2 cups black-eyed peas dry,\r\n1 Small habanero,\r\n3 ounces red bell pepper approximately half of one red bell pepper,\r\n1 small onion finely chopped,\r\n4 tablespoons crayfish (unblended) If you have it in the ground form you need 2 tablespoons,\r\nsalt to taste,\r\n1 chicken bouillon cube,\r\n1/4 cup water for blending – a little extra might be required,\r\nvegetable oil Enough for deep frying', '1. Soak the beans in room temperature water for about 15 to 20 minutes until the skin is swollen.\r\n2. Drain the water and place the beans in the food processor. Pulse the food processor a few times to remove the skin from the beans.\r\n3. Pour the beans into a large bowl, add enough water, and gently swirl the beans around so the skin can float. Discard the skin into a colander. Repeat this process until the beans are clean.\r\n4. Pour the clean beans into a blender, add the water, red bell pepper, habanero pepper, salt, bouillon powder, and crayfish, and blend until smooth.\r\n5. Pour the batter into a large bowl and whisk it until it’s light and fluffy – hand whisk for about 3 to 4 minutes, or use an electric hand mixer for about a minute or two.\r\n6. Add the finely diced onion and gently fold with a wooden spoon or spatula in one direction.\r\n7. Heat some oil (enough to fry the Akara) in a pan on medium to high heat. Drop heaping tablespoons of batter into the hot oil, frying in batches to prevent overcrowding. Flip once or twice to ensure even browning—fry the Akara for about five to six minutes, or until golden brown on all sides.\r\n8. Before removing any Akara from the oil, gently press them down to remove any excess oil.\r\n9. Remove the Akara from the pan and drain on a paper towel-lined plate.\r\n10. Serve with bread, pap, oatmeal, yogurt, or other desired side.', 'African', 'Breakfast', 'Akara (Black-eyed beans)'),
(57, '15 minutes', '1 hr', '1hr 15 minutes', '6', 'egusi.jpg', '1 cup blended onions (about 3- 5 and fresh chilies, to taste),\r\n4 cups egusi (melon seeds, ground or milled),\r\n1⁄2 – 1 cup palm oil,\r\n2 teaspoons fresh Une (Iru, locust beans),\r\nSalt (to taste),\r\nGround crayfish (to taste),\r\n7– 8 cups stock,\r\nCooked Meat & fish (quantity and variety to personal preference),\r\n2 cups cut pumpkin leaves,\r\n1 cup waterleaf (cut),\r\n3 tablespoons bitter leaf (washed)', '1. Prepare the egusi paste\r\n2. Blend egusi seeds and onion mixture. Set aside.\r\n3. In a large pot, heat the palm oil on medium for a minute and then add the Une.\r\n4. Slowly add the stock and set on low heat to simmer.\r\n5. Scoop teaspoon size balls of the egusi paste mixture into the stock. Be sure to keep ball shape.\r\n6. Leave to simmer for 20 – 30 minutes so the balls cook through.\r\n7. Add the meat and fish and other bits which you’d like to use.\r\n8. Add cut-up pumpkin leaves. \r\n9. Add the waterleaf.\r\n10. Stir and put a lid on the pot and allow cook for 7–10 minutes, till the leaves wilt.\r\n11. Add the bitter leaf.  Leave the lid off while the cooking finishes for another 5-10 minutes.\r\n12. Stir, check seasoning and adjust accordingly.', 'African', 'MainDishes', 'Egusi soup'),
(58, '10 min', '20 min', '30 min', '1', 'bole.jpg', '2 ripe plantain,\r\n1 whole mackerel or Titus fish,\r\nSalt to taste,\r\nOven or an open grill', '1. Peel off the skin of your plantain\r\n2. Make a slit on both sides of the plantain\r\n3. Rub a little salt evenly on the plantains\r\n4. Place the plantains on the grill rack and set aside while you work on your fish\r\n5. Cut a whole fish into 2 equal parts\r\n6. Wash and remove all the dirt thoroughly\r\n7. Make a slit on both sides of the fish, so that the seasoning can penetrate inside the fish\r\n8. In a separate bowl, mix some salt, seasoning cube and some chili flakes\r\n9. Rub the mixture evenly on both sides of the fish\r\n10. Place the fish on the grill rack together with the plantain\r\n11. Pre-heat your oven or grill at 170° for about 5 minutes\r\n12. Transfer the plantain and the fish into the preheated oven\r\n13. Allow to grill for about 20 minutes, while turning at intervals until all sides are perfectly roasted\r\n14. After 20 minutes, your Bole and grilled fish is ready', 'African', 'Snacks', 'Bole (roasted plantain and sauce)'),
(59, '10 min', '40 min', '50 min', '4', 'gizdodo.jpg', '1 Pound Gizzards,\r\n2 Plantains Ripe,\r\n4 Tomatoes Any Ripe and juicy Tomato will work,\r\nVegetable Oil Enough for frying,\r\nChicken stock,\r\n1 Teaspoon Curry Powder Divided in two,\r\n1 Tsp Thyme Divided in two,\r\nWater For boiling the Gizzards,\r\n2 Seasoning Cubes,\r\nSalt to Taste,\r\nGreen Bell Pepper, Yellow Bell Pepper and Orange bell peppers Diced,\r\n1 Habanero pepper Minced,\r\n1 Large Onion (Diced) Divided in two', '1. Wash and clean the Gizzards thoroughly\r\n2. Place the Gizzards inside the cooking Pot add the diced onions,1 seasoning cube Curry powder, Thyme, and Salt to taste. Add water to the same level as the 3. Gizzards and cook for about 40 minutes or until tender.\r\n4. Preheat some cooking Oil and fry the Gizzards till brown. Remove from Oil and set aside.\r\n5. Peel and cut the Plantain into ‘cube-like’ pieces, sprinkle with a pinch of salt and fry till golden brown.\r\n6. Put about 4 Tablespoons of cooking Oil into a Pan, add and stir-fry the Onions for about 2 minutes.  Add the diced Tomatoes and Minced Habanero pepper.  Fry for 3 to 5 minutes or anywhere in between. \r\n7. If too thick add a bit of chicken stock or water to loosen it up if necessary. 8. Add 1 Seasoning Cube, curry powder, Thyme, and Salt to taste. \r\n9. Finally, add the Gizzards, the Fried Plantains, and the diced bell peppers. 10. Stir together thoroughly, leave to simmer for 3 to 5 minutes and you are done.\r\n11. Serve and enjoy ”as is” or serve as a side to Rice, Couscous, Spaghetti or any other meal of your choice.', 'African', 'Snacks', 'Gizdodo'),
(60, '20 mins', '10 mins', '30 mins', '6 servings', 'chin.jpg', '5 ounces (150ml) whole milk,\r\n1 teaspoon (5ml) vanilla extract,\r\n14.1 ounces all-purpose flour (400g; 3 cups plus 2 tablespoons),\r\n3.5 ounces sugar (100g; 1/2 cup),\r\n1 1/2 teaspoons (6g) baking powder,\r\n1 teaspoon (3g) Diamond Crystal kosher salt; for table salt use half as much by volume or the same weight,\r\n2 teaspoons (4g) freshly grated lemon or orange zest,\r\n1/2 teaspoon freshly grated nutmeg,\r\n3.6 ounces unsalted butter (100g; 7 tablespoons), cold ,\r\n2 quarts (1.9L) vegetable oil, for frying', '1. In a small bowl, whisk together milk and vanilla extract until well combined and set aside.\r\n2. In a large bowl, whisk together flour, sugar, baking powder, salt, zest, and nutmeg until thoroughly combined. Using the large holes of a box grater, grate butter over flour mixture. Using your hands, toss butter with flour mixture until butter is evenly distributed.\r\n3. In the center of the butter-flour mixture, make a well about 4-inches wide. Slowly pour milk mixture into the well. Using a flexible spatula or wooden spoon, gradually stir butter-flour mixture into milk mixture until combined. Using your hands, knead dough against sides of bowl or on a lightly-floured work surface until it comes together in a soft, but not sticky, ball. Cover dough with plastic wrap or a clean kitchen towel and rest for 10 minutes. (Alternatively, shape dough into a flat, round disk, wrap tightly in plastic wrap, and refrigerate for up to 2 days or freeze for up to 6 months; bring to room temperature before rolling).  \r\n4. On a lightly-floured work surface, divide dough into 4 equal portions (about 195g each), and shape each into a ball. Working with one ball of dough at a time, roll out dough to form a 5-inch circle about 1/4 inch thick, adding more flour as needed underneath and on top of dough to prevent sticking. Using a sharp knife or pizza wheel, cut dough into 1/2-inch-wide diamonds, dipping the wheel or knife in flour as needed to keep dough from sticking. Transfer dough pieces to a lightly floured rimmed baking sheet, dust with flour, and gently toss to prevent sticking. Repeat with remaining dough balls\r\n5. Line a large strainer with paper towels. In a wok or large Dutch oven, heat oil over medium-high heat to 360°F (180°C). Divide the dough pieces into roughly 3 or 4 batches. Working with one batch of dough pieces at a time, add pieces to hot oil using a spider or slotted spoon and fry, turning pieces as they cook, until golden brown on both sides, about 3 minutes. Transfer chin chin to prepared strainer. \r\n6. Return oil to 360°F (180°C) and repeat frying with remaining batches of dough. Transfer chin chin to a serving bowl and serve warm or let cool completely, about 15 to 20 minutes.', 'African', 'Snacks', 'Chin chin'),
(61, '10 min', '30 mins', '40 mins', '3', 'ewaRiro.jpg', '3 cups black-eyed peas,\r\n1 red bell pepper,\r\n1 medium onion,\r\n1 roasted Turkey wing,\r\n1 habanero pepper,\r\n1 tablespoon crayfish,\r\n1/2 tablespoon seasoning powder,\r\n1/4 cup palm oil or to taste,\r\n6 to 9 cups water,\r\nsalt to taste', '1. Pick out the debris in the Beans. Then rinse well and drain.\r\n2. Put the beans inside the pot together with the bell pepper, habanero, onion, and smoked turkey wings. add water and leave to come to a rolling boil over high heat.\r\n3. Reduce the heat to medium-low and continue to cook until the beans become tender. about one hour. a little more or less.\r\n4. Remove the bell pepper, habanero, and onion Blend and add to the beans.\r\n5. Remove the smoked turkey, debone, cut the meat into small pieces, and put it back inside the beans.\r\n6. Add the salt, seasoning powder (seasoning cube), crayfish, and palm oil. Add water if necessary and stir well until everything is well combined.\r\n7. Leave to simmer for about 3 to 5 minutes and serve with Plantains, Bread, or Garri. Enjoy!', 'African', 'MainDishes', 'Stewed beans(ewa riro)'),
(62, '30 mins', '45 mins', '1hr 15 mins', '6', 'moiMoi.jpg', 'Black-eyed Peas or Honey Beans – Best to use black-eyed peas or honey beans (Ewa oloyin),\r\nPeppers – It’s best to use a combination of peppers like red bell peppers (tatashe) and scotch bonnet(rodo) for a deeper flavor profile,\r\nOnion – Onions, as always, bring out the flavor in the food.,\r\nCrayfish – you can ground the dry crayfish with the beans or use powdered crayfish.,\r\nVegetable Oil/Palm oil – You can use palm oil, vegetable oil, or a mixture. ,\r\nChicken bouillon Cubes – Add this for taste.,\r\nFish – This is optional but a great addition. The fish is boiled and cut into chunks. I like to use Mackerel or Salmon.,\r\nHard-boiled Eggs – Also a great addition!,\r\nBoiled beef liver – This is also optional. It will make a great filing in the mix. I love it because beef liver is nutrient-dense. ,\r\nSalt – Add salt to taste', '1. Soak the beans. It would be best to soak your beans for about 10 to 20 minutes. Dryer beans tend to be ready faster, while less dry beans will take a little longer.\r\n2. Peel your beans. You can peel your beans manually by rubbing them together between your palms. That is a long process, so I have found a shortcut for peeling. I use a food processor. This is a fast way to peel your beans.\r\n3. Sieve the skin of the beans out. After peeling, wash your beans and sieve out the skin until you get clean beans. The skin would float itself while the seed would go down. You can soak the beans for 10 minutes more to make them softer.\r\n4. Blend the beans and other ingredients – Add the beans into the blender with pepper and onions. Add bouillon cubes, salt, and crayfish. Add a cup of water to blend.\r\n5. Turn the batter into a bowl. Inside the batter, add the groundnut oil and mix.\r\n6. Add fish chunks or liver. You can add boiled fish already cut into chunks or pour in liver cut into small pieces. Keep mixing.\r\n7. Prepare the bowls – Depending on what you want to use for your Moi Moi, wash it and oil the plates. I used Ramekins Bakeware for this recipe.\r\n8. Portion the batter to the bowls. \r\n9. Add the boiled egg on top. Add your boiled egg on top. You don’t have to push it deep into the mix.\r\n10. Put the pot on the stove and add boiled water.\r\n11. Arrange the Moi Moi in the pot and cover. Allow it to steam for like 45 minutes. If you notice that the water in the pot has dried up, carefully add more water.\r\n12. Carefully remove the Moi Moi from the plate and enjoy.', 'African', 'Snacks', 'Moin moin'),
(63, '20 mins', '20 mins', '40 mins', '4', 'ekpang.jpg', '500g cocoyam,\r\n250g Water Yam (Optional),\r\nA big bunch of tender cocoyam leaves,\r\nPumpkin leaves and,\r\nScent leaves (nchanwu, efirin),\r\nPalm oil: a generous quantity,\r\nA handful crayfish,\r\n3 medium onions,\r\n2 milk cups (300g shelled or 500g unshelled) Periwinkles,\r\nAssorted Beef & Offal,\r\nDried fish,\r\nSnail (Optional),\r\nPepper & Salt to taste,\r\n2 stock cubes', '1. Rinse and cook the beef, offals and dry fish with the seasoning till done.\r\n2. Peel, wash and grate the cocoyam and water yam (if you will be using this). Mix the two together and set aside.\r\n3. Prepare the pot by rubbing a generous amount of red palm oil on the insides of the pot.\r\n4. Rinse the tender cocoyam leaves and tear into medium pieces. If using pumpkin leaves, wash these and set aside.\r\n5. Blend the pepper and crayfish and set aside.\r\n6. Wash the shelled or unshelled periwinkles.\r\n7. Rinse and slice the scent leaves into tiny pieces.\r\n8. If you will be using unshelled periwinkles, place these at the base of the well-oiled pot.\r\n9. Scoop a small quantity of the grated cocoyam into a piece of the torn cocoyam leaf or one pumpkin leaf. Wrap the cocoyam with the leaf and place in the pot. 10. Repeat this procedure till all the grated cocoyam (and water yam) is exhausted.\r\n11. Add the pepper, crayfish, onions, shelled periwinkles and assorted beef.\r\n12. Add hot water to the level of the pot contents and set to cook on medium heat for 20 minutes.\r\n13. Now, add the scent leaves, a generous amount of palm oil and salt to taste. 14. Cook for more 5 minutes and the Ekpang Nkwukwo is done.\r\n15. Leave to stand for 5 minutes and stir.', 'African', 'MainDishes', 'Ekpang nkukwo');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `recipes`
--
ALTER TABLE `recipes`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `recipes`
--
ALTER TABLE `recipes`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=94;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
